# Generated by Django 4.2.6 on 2023-10-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='begin_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='termination_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
