# Generated by Django 4.2.6 on 2023-10-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_start_date_alter_discount_begin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
