# Generated by Django 4.2.6 on 2023-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
