# Generated by Django 4.2.6 on 2023-10-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_delete_sale'),
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesperson',
        ),
    ]
